attestationreport: introduce generic manifests
Instead of a fix RTM Manifest, OS Manifest and App Manifests,
the CMC now accepts a list of linked 'Manifests' with a
root manifest linking to itself and arbitrary many dependent
manifests organized in arbitrary layers. This allows to
represent any software stack and platform.

Signed-off-by: Simon Ott <simon.ott@aisec.fraunhofer.de>

diff --git a/example-setup/generate-container-manifest b/example-setup/generate-container-manifest
--- a/example-setup/generate-container-manifest
+++ b/example-setup/generate-container-manifest
@@ -7,12 +7,12 @@ dir="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)"
 source "${dir}/utils.sh"
 export PATH=${PATH}:${HOME}/go/bin
 
-if [[ "$#" -lt 5 ]]; then
+if [[ "$#" -lt 4 ]]; then
   # The target depends on the client, examples:
   # docker/ctr:     docker.io/library/ubuntu:22.04
   # docker compose: docker-compose.yaml
   # runc:           /path/to/runtime-bundle
-  echo "Usage: ./update-container-manifest-live <target> <data-folder> <cmc-folder> <cbor|json> <container-client> [<container arguments>]"
+  echo "Usage: $(basename "$0") <data-folder> <container> <cmc-folder> <container-client> [<container arguments>]"
   exit 1
 fi
 
@@ -32,34 +32,41 @@ for arg in "$@"; do
 done
 
 # Set all parameters
-target="$1"
-shift
 data=$(set -e; abs_path "$1")
 shift
-cmc=$(set -e; abs_path "$1")
+target="$1"
 shift
-ser="$1"
+cmc=$(set -e; abs_path "$1")
 shift
 client="$1"
 shift
 args="$@"
 
-input="${data}/metadata-raw"
-tmp="${data}/metadata-tmp"
-output="${data}/metadata-signed"
+input="${data}/metadata-templates"
+out="${data}/metadata-raw"
+
 runtime="${cmc}/tools/containerd-shim-cmc-v1/containerd-shim-cmc-v1"
 runc_config="/etc/runc-measure-conf.json"
 target="${target%/}"
+device_description="${out}/device.description.json"
 
+if [[ ! -d "${data}" ]]; then
+  echo "Data directory ${data} does not exist. Did you run the setup-cmc script? Abort.."
+  exit 1
+fi
+
+if [[ ! -f "${device_description}" ]]; then
+    echo "Error: Device description ${device_description} does not exist. Run generate-device-description first"
+    exit 1
+fi
 
 echo "Creating reference values for container: ${target} with args ${args}"
 echo "Using ${data} as directory for local data"
 
-# Delete temporary manifests
-rm -rf "${tmp:?}"/*
+mkdir -p "${out}"
 
 # Temporarily configure runc to generate reference values
-if [ ! -f "${runc_config}" ]; then
+if [[ ! -f "${runc_config}" ]]; then
     exists=false
     echo "{\"generateRefVals\":\"true\"}" | tee "${runc_config}"
 else
@@ -113,15 +120,13 @@ else
 fi
 
 # Restore the original runc config
-if [ "${exists}" = true ] ; then
+if [[ "${exists}" = true ]] ; then
  echo "${original_json}" | sudo tee "${runc_config}"
 else
   sudo rm "${runc_config}"
 fi
 
 refvals=$(cat /tmp/container-refs)
-
-# if containers not set, set it to the single container
 
 # In some scenarios, e.g. docker-compose, we have more than one container and have to iterate over all
 num_containers=$(echo "${refvals}" | jq length)
@@ -134,9 +139,10 @@ for ((i = 0; i < num_containers; i++)); do
     refval=$(echo "${refvals}" | jq -r ".[$i].referenceValue")
     config=$(echo "${refvals}" | jq -r ".[$i].ociSpec")
 
-    # App Manifest: Replace existing reference values and OCI config with new reference values in the App Manifest
-    json=$(cat "${input}/app.manifest.json")
-    json=$(echo "${json}" | jq 'del(.referenceValues[])')
+    # App Manifest: load
+    json=$(cat "${input}/manifest.json")
+
+    # App Manifest: Insert reference values and OCI config
     json=$(echo "${json}" | jq --argjson ver "[${refval}]" '.referenceValues += $ver')
     json=$(echo "${json}" | jq --argjson cfg "${config}" '.ociSpec = $cfg')
 
@@ -150,14 +156,23 @@ for ((i = 0; i < num_containers; i++)); do
     json=$(echo "${json}" | jq ".name = \"${container}-${sha256}\"")
     json=$(echo "${json}" | jq ".referenceValues[0].name += \": ${container}\"")
 
+    # App Manifest: Set other properties
+    setjson "json" "version"               "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
+    setjson "json" "developerCommonName"   "test developer"
+    setjson "json" "validity.notBefore"    "$(date -u +"%Y-%m-%dT%H:%M:%SZ" -d "-1 day")"
+    setjson "json" "validity.notAfter"     "$(date -u +"%Y-%m-%dT%H:%M:%SZ" -d "+2 years")"
+    setjson "json" "description"           "App Manifest"
+    setarr  "json" "baseLayers"            "de.test.os"
+    setjson "json" "certLevel"             1
+
     # App Manifest: Store
-    echo "Writing ${input}/${container_name}-${sha256}.manifest.json"
-    printf "%s\n" "${json}" > "${input}/${container_name}-${sha256}.manifest.json"
+    echo "Writing ${out}/${container_name}-${sha256}.manifest.json"
+    printf "%s\n" "${json}" > "${out}/${container_name}-${sha256}.manifest.json"
 
     # App Description: Create corresponding app description
-    appdesc=$(cat "${input}/app.description.json")
+    appdesc=$(cat "${input}/manifest.description.json")
     appdesc=$(echo "${appdesc}" | jq ".name = \"${container}-${sha256}.description\"")
-    appdesc=$(echo "${appdesc}" | jq ".appManifest = \"${container}-${sha256}\"")
+    appdesc=$(echo "${appdesc}" | jq ".manifest = \"${container}-${sha256}\"")
     echo "Adding environment variables"
     for j in "${!keys[@]}"; do
         envs="{\"key\": \"${keys[${j}]}\", \"value\": \"${values[${j}]}\"}"
@@ -166,38 +181,17 @@ for ((i = 0; i < num_containers; i++)); do
     done
 
     # Device Description: Add/replace app description to/in device description
-    devdesc=$(cat "${input}/device.description.json")
-    exists=$(echo "${devdesc}" | jq "any(.appDescriptions[]; .name == \"${container}-${sha256}.description\")")
+    devdesc=$(cat "${device_description}")
+    exists=$(echo "${devdesc}" | jq "any(.descriptions[]; .name == \"${container}-${sha256}.description\")")
     if [[ "${exists}" = false ]]; then
       echo "Adding app description to device description"
     else
       echo "Replacing existing app description"
-      devdesc=$(echo "$devdesc" | jq ".appDescriptions |= map(select(.name != \"${container}-${sha256}.description\"))")
+      devdesc=$(echo "$devdesc" | jq ".descriptions |= map(select(.name != \"${container}-${sha256}.description\"))")
     fi
-    devdesc=$(echo "${devdesc}" | jq --argjson desc "[${appdesc}]" '.appDescriptions += $desc')
+    devdesc=$(echo "${devdesc}" | jq --argjson desc "[${appdesc}]" '.descriptions += $desc')
 
     # Device Description: Store
-    echo "Writing ${input}/device.description.json"
-    printf "%s\n" "${devdesc}" > "${input}/device.description.json"
-
-    # Sign the metadata*
-    key="${data}/pki/signing-cert-key.pem"
-    chain="${data}/pki/signing-cert.pem,${data}/pki/ca.pem"
-
-    # Convert to CBOR if specified
-    if [[ "${ser,,}" = "json" ]]; then
-      echo "using json serialization"
-      cp "${input}/${container_name}-${sha256}.manifest.json" "${tmp}/${container_name}-${sha256}.manifest.json"
-      cp "${input}/device.description.json" "${tmp}/device.description.json"
-    elif [[ "${ser,,}" = "cbor" ]]; then
-      echo "using cbor serialiation"
-      cmc-converter -in "${input}/${container_name}-${sha256}.manifest.json" -out "${tmp}/${container_name}-${sha256}.manifest.cbor" -outform cbor
-      cmc-converter -in "${input}/device.description.json" -out "${tmp}/device.description.cbor" -outform cbor
-    else
-      echo "serialization format ${ser} is not supported"
-      exit 1
-    fi
-
-    cmc-signing-tool -in "${tmp}/${container_name}-${sha256}.manifest.${ser}" -out "${output}/${container_name}-${sha256}.manifest.${ser}" -keys "${key}" -x5cs "${chain}"
-    cmc-signing-tool -in "${tmp}/device.description.${ser}" -out "${output}/device.description.${ser}" -keys "${key}" -x5cs "${chain}"
+    echo "Writing ${device_description}"
+    printf "%s\n" "${devdesc}" > "${device_description}"
 done
