example-setup: updated scripts
Fix all shellcheck warnings

Signed-off-by: Simon Ott <simon.ott@aisec.fraunhofer.de>

diff --git a/example-setup/setup-full-simple b/example-setup/setup-full-simple
--- a/example-setup/setup-full-simple
+++ b/example-setup/setup-full-simple
@@ -1,52 +1,53 @@
 #!/bin/bash
 
-set -e
+set -euo pipefail
 
-function abs_path() {
-  if [ -d "$(dirname "$1")" ]
+trap '[ $? -eq 0 ] && exit 0; printf "%s failed\n" "$0"' EXIT
+export PATH=${PATH}:${HOME}/go/bin
+
+abs_path() {
+  if [[ -d "$(dirname "$1")" ]]
   then
-    echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
+    echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")" || true
   fi
 }
 
-if [ "$#" -ne 3 ]; then
+if [[ "$#" -ne 3 ]]; then
    echo "Usage: ./setup-full-simple <cmc-folder> <data-folder> <cbor|json>"
    exit
 fi
 
-CMC="$(abs_path $1)"
-DATA="$(abs_path $2)"
-SER="$3"
+cmc=$(set -e; abs_path "$1")
+data=$(set -e; abs_path "$2")
+ser="${3}"
 
-if [ ! -d "$CMC" ]; then
+if [[ ! -d "${cmc}" ]]; then
   echo "CMC directory does not exist. Did you clone the repository? Abort.."
   exit 1
 fi
 
-if [ -d "$DATA" ]; then
+if [[ -d "${data}" ]]; then
   echo "Data directory does already exist. Please choose a new directory. Abort.."
   exit 1
 fi
 
-echo "Using CMC: $CMC"
-echo "Using $DATA as directory for local data"
-
-export PATH=$PATH:$HOME/go/bin
+echo "Using CMC: ${cmc}"
+echo "Using ${data} as directory for local data"
 
 # Create a folder for the cmc configuration and metadata
-mkdir -p $DATA
+mkdir -p "${data}"
 
 # Install dependencies
 sudo apt install -y moreutils golang-cfssl build-essential zlib1g-dev libssl-dev jq
 
 # Intall tpm-pcr-tools
-git clone https://github.com/Fraunhofer-AISEC/tpm-pcr-tools.git $DATA/tpm-pcr-tools
-cd $DATA/tpm-pcr-tools
+git clone https://github.com/Fraunhofer-AISEC/tpm-pcr-tools.git "${data}/tpm-pcr-tools"
+cd "${data}/tpm-pcr-tools"
 make
 sudo make install
 
 # Build CMC
-cd $CMC
+cd "${cmc}"
 echo "Building CMC.."
 go build ./...
 
@@ -55,56 +56,10 @@ echo "Installing CMC"
 go install ./...
 
 # Copy metadata templates
-cp -r $CMC/example-setup/* $DATA
+cp -r "${cmc}/example-setup/"* "${data}"
 
 # Generate a PKI suitable for your needs. You can use the simple PKI example-setup for testing:
-$DATA/setup-pki-simple -i $DATA -o $DATA/pki
+"${data}/setup-pki-simple" -i "${data}" -o "${data}/pki"
 
-# Parse the values of the RTM PCRs from the kernel's binary bios measurements as reference values
-referenceValues=$(sudo parse-srtm-pcrs -p 0,1,2,3,4,5,6,7 -f json)
-
-# Delete existing reference values in the RTM Manifest
-jq 'del(.referenceValues[])' $DATA/metadata-raw/rtm.manifest.json | sponge $DATA/metadata-raw/rtm.manifest.json
-
-# Add new reference values
-jq --argjson ver "$referenceValues" '.referenceValues += $ver' $DATA/metadata-raw/rtm.manifest.json | sponge $DATA/metadata-raw/rtm.manifest.json
-
-# Do this for the OS manifest as well
-referenceValues=$(sudo parse-srtm-pcrs -p 8,9 -f json)
-jq 'del(.referenceValues[])' $DATA/metadata-raw/os.manifest.json | sponge $DATA/metadata-raw/os.manifest.json
-jq --argjson ver "$referenceValues" '.referenceValues += $ver' $DATA/metadata-raw/os.manifest.json | sponge $DATA/metadata-raw/os.manifest.json
-
-# Sign the metadata*
-IN=$DATA/metadata-raw
-TMP=$DATA/metadata-tmp
-OUT=$DATA/metadata-signed
-KEY=$DATA/pki/signing-cert-key.pem
-CHAIN=$DATA/pki/signing-cert.pem,$DATA/pki/ca.pem
-
-rm -rf $TMP
-rm -rf $OUT
-
-mkdir -p $TMP
-mkdir -p $OUT
-
-if [ "${SER,,}" = "json" ]; then
-  echo "using json serialization"
-  cp $IN/rtm.manifest.json        $TMP/rtm.manifest.json
-  cp $IN/os.manifest.json         $TMP/os.manifest.json
-  cp $IN/device.description.json  $TMP/device.description.json
-  cp $IN/device.config.json       $TMP/device.config.json
-elif [ "${SER,,}" = "cbor" ]; then
-  echo "using cbor serialiation"
-  cmc-converter -in $IN/rtm.manifest.json        -out $TMP/rtm.manifest.cbor       -outform cbor
-  cmc-converter -in $IN/os.manifest.json         -out $TMP/os.manifest.cbor        -outform cbor
-  cmc-converter -in $IN/device.description.json  -out $TMP/device.description.cbor -outform cbor
-  cmc-converter -in $IN/device.config.json       -out $TMP/device.config.cbor      -outform cbor
-else
-  echo "serialization format ${SER} is not supported"
-  exit 1
-fi
-
-cmc-signing-tool -in $TMP/rtm.manifest."${SER}"        -out $OUT/rtm.manifest."${SER}"        -keys $KEY -x5cs $CHAIN
-cmc-signing-tool -in $TMP/os.manifest."${SER}"         -out $OUT/os.manifest."${SER}"         -keys $KEY -x5cs $CHAIN
-cmc-signing-tool -in $TMP/device.description."${SER}"  -out $OUT/device.description."${SER}"  -keys $KEY -x5cs $CHAIN
-cmc-signing-tool -in $TMP/device.config."${SER}"       -out $OUT/device.config."${SER}"       -keys $KEY -x5cs $CHAIN
+# Update and sign metadata
+"${data}/update-full-simple" "${data}" "${ser}"
diff --git a/example-setup/setup-pki-simple b/example-setup/setup-pki-simple
--- a/example-setup/setup-pki-simple
+++ b/example-setup/setup-pki-simple
@@ -1,24 +1,25 @@
 #!/bin/bash
 
-set -e
+set -euo pipefail
 
-DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)"
-CMC_DIR="$DIR/.."
+trap '[ $? -eq 0 ] && exit 0; printf "%s failed\n" "$0"' EXIT
+dir="$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd -P)"
 
-IN="$CMC_DIR/example-setup"
-OUT="$DIR"
+cmc="${dir}/.."
+input="${cmc}/example-setup"
+out="${dir}"
 
 print_usage() {
-  printf "Usage: ./setup_simple_pki [-i <input-dir>] [-o <output-dir] [-h]\n"
+  printf "Usage: ./setup-pki-simple [-i <input-dir>] [-o <output-dir] [-h]\n"
 }
 
 while getopts 'i:o:h' flag; do
   case "${flag}" in
     i)
-        IN="${OPTARG}"
+        input="${OPTARG}"
         ;;
     o)
-        OUT="${OPTARG}"
+        out="${OPTARG}"
         ;;
     h)
         print_usage
@@ -29,27 +30,27 @@ while getopts 'i:o:h' flag; do
   esac
 done
 
-if [ ! -d "$IN" ]; then
-    echo "Input directory $IN does not exist"
+if [[ ! -d "${input}" ]]; then
+    echo "Input directory ${input} does not exist"
     exit 1
 fi
 
-echo "Using $IN as input directory"
-echo "Using $OUT as output directory"
+echo "Using ${input} as input directory"
+echo "Using ${out} as output directory"
 
-mkdir -p $OUT
+mkdir -p "${out}"
 
 # Set up root CA
-cfssl gencert -initca "$IN/cfssl-ca.json" | cfssljson -bare "$OUT/ca"
+cfssl gencert -initca "${input}/cfssl-ca.json" | cfssljson -bare "${out}/ca"
 
 # Generate key and CSR for metadata signing
-cfssl genkey -config "$IN/cfssl-ca-config.json" -profile leafcert "$IN/cfssl-leaf.json" | cfssljson -bare "$OUT/signing-cert"
+cfssl genkey -config "${input}/cfssl-ca-config.json" -profile leafcert "${input}/cfssl-leaf.json" | cfssljson -bare "${out}/signing-cert"
 
 # Sign CSR and generate certificate for metadata signing
-cfssl sign -ca "$OUT/ca.pem" -ca-key "$OUT/ca-key.pem" -profile leafcert -config $IN/cfssl-ca-config.json "$OUT/signing-cert.csr" | cfssljson -bare "$OUT/signing-cert"
+cfssl sign -ca "${out}/ca.pem" -ca-key "${out}/ca-key.pem" -profile leafcert -config "${input}/cfssl-ca-config.json" "${out}/signing-cert.csr" | cfssljson -bare "${out}/signing-cert"
 
 # Generate key and CSR for EST server
-cfssl genkey -config "$IN/cfssl-ca-config.json" -profile leafcert "$IN/cfssl-est.json" | cfssljson -bare "$OUT/est"
+cfssl genkey -config "${input}/cfssl-ca-config.json" -profile leafcert "${input}/cfssl-est.json" | cfssljson -bare "${out}/est"
 
 # Sign CSR and generate certificate for EST server
-cfssl sign -ca "$OUT/ca.pem" -ca-key "$OUT/ca-key.pem" -profile leafcert -config $IN/cfssl-ca-config.json "$OUT/est.csr" | cfssljson -bare "$OUT/est"
+cfssl sign -ca "${out}/ca.pem" -ca-key "${out}/ca-key.pem" -profile leafcert -config "${input}/cfssl-ca-config.json" "${out}/est.csr" | cfssljson -bare "${out}/est"
diff --git a/example-setup/update-app-manifest b/example-setup/update-app-manifest
--- a/example-setup/update-app-manifest
+++ b/example-setup/update-app-manifest
@@ -1,11 +1,14 @@
 #!/bin/bash
 
-set -e
+set -euo pipefail
 
-function abs_path() {
-  if [ -d "$(dirname "$1")" ]
+trap '[ $? -eq 0 ] && exit 0; printf "%s failed\n" "$0"' EXIT
+export PATH=${PATH}:${HOME}/go/bin
+
+abs_path() {
+  if [[ -d "$(dirname "$1")" ]]
   then
-    echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
+    echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")" || true
   fi
 }
 
@@ -18,96 +21,53 @@ extendarr() {
   	json="$(echo "${json}" | jq ".${key} += [${param}]")"
 }
 
-if [ "$#" -ne 2 ]; then
+if [[ "$#" -ne 2 ]]; then
    echo "Usage: ./update-app-manifest <data-folder> <cbor|json>"
    exit 1
 fi
 
-data="$(abs_path $1)"
+data=$(set -e; abs_path "$1")
+input="${data}/metadata-raw"
+tmp="${data}/metadata-tmp"
+output="${data}/metadata-signed"
 ser="${2}"
 
-if [ ! -d "${data}" ]; then
+if [[ ! -d "${data}" ]]; then
   echo "Data directory ${data} does not exist. Did you run the setup-full-simple script? Abort.."
   exit 1
 fi
 
 echo "Using ${data} as directory for local data"
 
-export PATH=$PATH:$HOME/go/bin
-
-# Delete existing reference values in manifest
-jq 'del(.referenceValues[])' ${data}/metadata-raw/app.manifest.json | sponge ${data}/metadata-raw/app.manifest.json
-
 # Load manifest
 json=$(cat "${data}/metadata-raw/app.manifest.json")
 
-# Hash apps on the system
-sources=(
-	"/usr/bin"
-	"/usr/sbin"
-)
-echo "Hashing apps and configuration.."
-for source in "${sources[@]}"; do
+# Calculate the IMA app reference values
+referenceValues=$(sudo calculate-ima-pcr -t 10 -i ima-ng -p /usr/bin)
 
-	echo "Hashing files in ${source}.."
-
-	# Check if the directory exists
-	if [[ ! -d "${source}" ]]; then
-		echo "[generate-app-manifests] Path ${source} does not exist."
-		exit 1
-	fi
-
-	# Hash the software artifacts
-	while IFS= read -r -d '' path; do
-		if [[ -f "${path}" ]]; then
-			out=$(sha256sum "${path}")
-			hash="${out%% *}"
-			filename=$(basename "${path}")
-			index=$(echo "${path}" | grep -b -o 'target/' | head -n 1 | cut -d':' -f1)
-			if [[ -n "${index}" ]]; then
-				description="${path:$((index + 6))}"
-			else
-				description=""
-			fi
-
-			ref="{
-					\"type\" : \"TPM Reference Value\",
-					\"name\" : \"${filename}\",
-					\"pcr\" : 10,
-					\"sha256\" : \"${hash}\",
-					\"description\" : \"${description}\"
-				}"
-
-			# Add reference value to manifests
-			extendarr "referenceValues" "${ref}"
-		fi
-	done < <(find "${source}" -type f -print0 2>/dev/null)
-done
-
-echo "Finished hashing"
-
-printf "%s\n" "${json}" > "${data}/metadata-raw/app.manifest.json"
+# Replace existing reference values with new reference values in the App Manifest
+json=$(cat "${input}/app.manifest.json")
+json=$(echo "${json}" | jq 'del(.referenceValues[])')
+json=$(echo "${json}" | jq --argjson ver "${referenceValues}" '.referenceValues += $ver')
+printf "%s\n" "${json}" > "${input}/app.manifest.json"
 
 # Sign the metadata*
-input=${data}/metadata-raw
-tmp=${data}/metadata-tmp
-output=${data}/metadata-signed
-key=${data}/pki/signing-cert-key.pem
-chain=${data}/pki/signing-cert.pem,${data}/pki/ca.pem
+key="${data}/pki/signing-cert-key.pem"
+chain="${data}/pki/signing-cert.pem,${data}/pki/ca.pem"
 
-rm -rf ${tmp}/app.manifest.*
-rm -rf ${out}/app.manifest.*
+rm -rf "${tmp}"/app.manifest.*
+rm -rf "${output}"/app.manifest.*
 
 # Convert to CBOR if specified
-if [ "${ser,,}" = "json" ]; then
+if [[ "${ser,,}" = "json" ]]; then
   echo "using json serialization"
-  cp ${input}/app.manifest.json        ${tmp}/app.manifest.json
-elif [ "${ser,,}" = "cbor" ]; then
+  cp "${input}/app.manifest.json" "${tmp}/app.manifest.json"
+elif [[ "${ser,,}" = "cbor" ]]; then
   echo "using cbor serialiation"
-  cmc-converter -in ${input}/app.manifest.json -out ${tmp}/app.manifest.cbor -outform cbor
+  cmc-converter -in "${input}/app.manifest.json" -out "${tmp}/app.manifest.cbor" -outform cbor
 else
   echo "serialization format ${ser} is not supported"
   exit 1
 fi
 
-cmc-signing-tool -in ${tmp}/app.manifest."${ser}" -out ${output}/app.manifest."${ser}" -keys "${key}" -x5cs "${chain}"
+cmc-signing-tool -in "${tmp}/app.manifest.${ser}" -out "${output}/app.manifest.${ser}" -keys "${key}" -x5cs "${chain}"
diff --git a/example-setup/update-app-manifest-live b/example-setup/update-app-manifest-live
--- a/example-setup/update-app-manifest-live
+++ b/example-setup/update-app-manifest-live
@@ -1,11 +1,14 @@
 #!/bin/bash
 
-set -e
+set -euo pipefail
 
-function abs_path() {
-  if [ -d "$(dirname "$1")" ]
+trap '[ $? -eq 0 ] && exit 0; printf "%s failed\n" "$0"' EXIT
+export PATH=${PATH}:${HOME}/go/bin
+
+abs_path() {
+  if [[ -d "$(dirname "$1")" ]]
   then
-    echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
+    echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")" || true
   fi
 }
 
@@ -18,56 +21,54 @@ extendarr() {
   json="$(echo "${json}" | jq ".${key} += [${param}]")"
 }
 
-if [ "$#" -ne 2 ]; then
-   echo "Usage: ./update-app-manifest <data-folder> <cbor|json>"
+if [[ "$#" -ne 2 ]]; then
+   echo "Usage: ./update-app-manifest-live <data-folder> <cbor|json>"
    exit 1
 fi
 
-data="$(abs_path $1)"
+data=$(set -e; abs_path "$1")
+input="${data}/metadata-raw"
+tmp="${data}/metadata-tmp"
+out="${data}/metadata-signed"
 ser="${2}"
 
-if [ ! -d "${data}" ]; then
+if [[ ! -d "${data}" ]]; then
   echo "Data directory ${data} does not exist. Did you run the setup-full-simple script? Abort.."
   exit 1
 fi
 
 echo "Using ${data} as directory for local data"
 
-export PATH=$PATH:$HOME/go/bin
-
 # Parse the IMA measurement lists
 referenceValues=$(sudo parse-ima-log)
 
 # Delete existing reference values in manifest
-jq 'del(.referenceValues[])' ${data}/metadata-raw/app.manifest.json | sponge ${data}/metadata-raw/app.manifest.json
+jq 'del(.referenceValues[])' "${data}/metadata-raw/app.manifest.json" | sponge "${data}/metadata-raw/app.manifest.json"
 
 # Insert new reference values
 json=$(cat "${data}/metadata-raw/app.manifest.json")
 while IFS= read -r element; do
-    json=$(echo "$json" | jq --argjson element "$element" '.referenceValues += [$element]')
+    json=$(echo "${json}" | jq --argjson element "${element}" '.referenceValues += [$element]')
 done < <(echo "${referenceValues}" | jq -c '.[]')
 printf "%s\n" "${json}" > "${data}/metadata-raw/app.manifest.json"
 
 # Sign the metadata*
-input=${data}/metadata-raw
-tmp=${data}/metadata-tmp
-output=${data}/metadata-signed
-key=${data}/pki/signing-cert-key.pem
-chain=${data}/pki/signing-cert.pem,${data}/pki/ca.pem
+key="${data}/pki/signing-cert-key.pem"
+chain="${data}/pki/signing-cert.pem,${data}/pki/ca.pem"
 
-rm -rf ${tmp}/app.manifest.*
-rm -rf ${out}/app.manifest.*
+rm -rf "${tmp}"/app.manifest.*
+rm -rf "${out}"/app.manifest.*
 
 # Convert to CBOR if specified
-if [ "${ser,,}" = "json" ]; then
+if [[ "${ser,,}" = "json" ]]; then
   echo "using json serialization"
-  cp ${input}/app.manifest.json        ${tmp}/app.manifest.json
-elif [ "${ser,,}" = "cbor" ]; then
+  cp "${input}/app.manifest.json" "${tmp}/app.manifest.json"
+elif [[ "${ser,,}" = "cbor" ]]; then
   echo "using cbor serialiation"
-  cmc-converter -in ${input}/app.manifest.json -out ${tmp}/app.manifest.cbor -outform cbor
+  cmc-converter -in "${input}/app.manifest.json" -out "${tmp}/app.manifest.cbor" -outform cbor
 else
   echo "serialization format ${ser} is not supported"
   exit 1
 fi
 
-cmc-signing-tool -in ${tmp}/app.manifest."${ser}" -out ${output}/app.manifest."${ser}" -keys "${key}" -x5cs "${chain}"
+cmc-signing-tool -in "${tmp}/app.manifest.${ser}" -out "${out}/app.manifest.${ser}" -keys "${key}" -x5cs "${chain}"
